; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
monitor_speed = 115200
upload_speed = 921600
platform_packages =
    toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
board_build.partitions = partitions.csv
lib_deps = 
    https://github.com/KeithHanson/ESPAsyncWebServer
    https://github.com/alanswx/ESPAsyncWiFiManager
    https://github.com/knolleary/pubsubclient
    https://github.com/bblanchon/ArduinoJson
    https://github.com/bblanchon/ArduinoStreamUtils
    https://github.com/YiannisBourkelis/Uptime-Library

    https://github.com/wemos/WEMOS_Motor_Shield_Arduino_Library
    https://github.com/xreef/PCF8574_library
    https://github.com/tobiasfaust/i2cdetect   

extra_scripts = 
    pre:scripts/prepareDataDir.py
build_flags =  
    -DASYNCWEBSERVER_REGEX
    -Ddbg=Serial
    !python scripts/build_flags.py git_branch
    !python scripts/build_flags.py git_repo

#####################################################################
[env:firmware_ESP8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = ${env.monitor_speed}
upload_speed = ${env.upload_speed}
board_build.filesystem = littlefs
lib_deps =
    ${env.lib_deps}
    https://github.com/me-no-dev/ESPAsyncTCP.git
lib_ignore =
        
build_flags = 
    ${env.build_flags}
    -D USE_PCF8574=1
    -D USE_TB6612=1
